### PR TITLE
Podspec for Video sdk version 1.0.0-beta2

### PR DESCRIPTION
**Pull request by ptankTwilio**

### CODE REVIEW

**Comment by ceaglest** [comment]
👍 Lets hold off on merging this until the QS changes are ready.

**Comment by AndrewBarba** [comment]
Hey guys I've been testing beta2 since this PR was put up and `.attach()` is not working well at all compared to beta1. With no code changes from beta1 to beta2 I can maybe get a video track to render via attach 1 out of 50 times. Incredibly inconsistent, especially in an app extension (specifically a iMessage app). Going to back to beta 1 everything works as expected regarding rendering.

**Comment by ceaglest** [comment]
@AndrewBarba thanks for the early feedback. We made some changes to renderer behavior to make our OpenGL and Metal implementations more consistent, and to prevent using GPU resources in the background at initialization time. Sounds like the issue you are having in an extension is that both renderers now pause rendering while the application is in the inactive state.

If you use beta1 and force the use of OpenGL rendering do you have any issues in your extension? That renderer would never render unless the application was active.

**Comment by AndrewBarba** [comment]
@ceaglest Thanks for the update! Yes it is in the extension that I am seeing this happen. It is an iMessage application with NO parent app, just an extension, which is allowed specifically for iMessage apps in the new app store

**Comment by ceaglest** [comment]
@AndrewBarba I appreciate your response. We did some investigation into this issue, and unfortunately the beta2 release will not support this use case properly. Our team will consider how to properly support extensions in future releases, especially given that our SDK is delivered in pre-compiled form. We have updated the beta2 release notes to mention this issue.

For `TVIVideoViewRenderer` we would prefer to to have automatic detection of application state (by default) so that developers do not need to worry about GPU related crashes in the background. In the future I could see adding a public API to enable / disable the renderer so that you could call it in response to extension lifecycle events.

**Comment by AndrewBarba** [comment]
@ceaglest Totally understand. Would really appreciate a re-visit of extensions in a future beta, I have an app thats pretty much ready to go otherwise :) Also happy to share code if it helps you guys test / see use cases.

**Pull request merged**
